target="template_release"
debug_symbols="no"
optimize="size_extra"
lto="full"
vulkan="no"
use_volk="no"
minizip="no"
accesskit="no"

# modules_enabled_by_default="no"
module_text_server_adv_enabled="no"
module_text_server_fb_enabled="yes"
module_mono_enabled="yes"
module_gdscript_enabled="no"
module_bmp_enabled="no"
module_csg_enabled="no"
module_cvtt_enabled="no"
module_dds_enabled="no"
module_enet_enabled="no"
module_etcpak_enabled="no"
module_fbx_enabled="no"
module_gltf_enabled="no"
module_physics_2d_enabled="no"
module_physics_3d_enabled="no"
module_godot_physics_2d_enabled="no"
module_godot_physics_3d_enabled="no"
module_jolt_enabled="no"
module_gridmap_enabled="no"
module_hdr_enabled="no"
module_interactive_music_enabled="no"
module_jpg_enabled="no"
module_jsonrpc_enabled="no"
module_ktx_enabled="no"
module_lightmapper_rd_enabled="no"
module_mbedtls_enabled="no"
module_meshoptimizer_enabled="no"
module_mobile_vr_enabled="no"
module_mp3_enabled="no"
module_msdfgen_enabled="no"
module_multiplayer_enabled="no"
module_navigation_2d_enabled="no"
module_navigation_3d_enabled="no"
module_noise_enabled="no"
module_objectdb_profiler_enabled="no"
module_ogg_enabled="no"
module_openxr_enabled="no"
module_raycast_enabled="no"
module_regex_enabled="no"
module_tga_enabled="no"
module_theora_enabled="no"
module_tinyexr_enabled="no"

module_upnp_enabled="no"

module_vhacd_enabled="no"
module_visual_shader_enabled="no"
module_vorbis_enabled="no"
module_webrtc_enabled="no"
module_websocket_enabled="no"
module_webxr_enabled="no"
module_xatlas_unwrap_enabled="no"
module_zip_enabled="no"

# Causes the template to fail building
# module_webp_enabled="no"
# deprecated="no"
# openxr="no"

# No build profile setup yet
# build_profile="/nvme/Dev/thief/kc-model-editor/kcme_build_config.gdbuild"
